name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_target: [unit-test, e2e-test]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --all-groups --frozen

      - name: Create secrets file from example
        run: cp .streamlit/secrets.example.toml .streamlit/secrets.toml

      - name: Run tests
        env:
          SUDO: ${{ secrets.SUDO || 'true' }}
        run: make ${{ matrix.test_target }}
